version: '3.8'

services:
  db:
    container_name: TuneVault
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=TuneVault_123!@# 
    ports:
      - "1433:1433" 
    volumes:
      - sql_data:/var/opt/mssql 

volumes:
  sql_data: